### ISSUE TITLE
Run Tests on PR

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/pymodaq_utils#10]
@malik-irain I can see no tests were triggered here on this PR. I guess I didn't specify the trigger on pull reaquest in the actions. Could you make sure the 4 packages: pymodaq, pymodaq_data, utils and gui are behaving the same? thx

_Originally posted by @seb5g in https://github.com/PyMoDAQ/pymodaq_utils/issues/8#issuecomment-2520656785_

**Comment by malik-irain** [comment]
It should be included in PR #11
